library(readr)
library(tidyr)
library(dplyr)
power <- read_delim(".\\data\\household_power_consumption.txt", col_names = TRUE, delim = ";", col_types = "ccnnnnnnn")
datepower<- power %>% mutate(datestr = paste(Date,Time))
datepower$datestr<- strptime(datepower$datestr,"%d/%m/%Y %H:%M:%S")
subpower <- datepower[datepower$datestr >= "2007-02-01" & datepower$datestr < "2007-02-03", ]
subpower<- subpower[1:2880,]
with(subpower, plot(datestr, Sub_metering_1, ylab = "Energy sub metering", xlab = "", main = "",type = "n"))
with(subpower, points(datestr,Sub_metering_1, col = 1, type = "l"))
with(subpower, points(datestr,Sub_metering_2, col = "red", type = "l"))
with(subpower, points(datestr,Sub_metering_3, col = "purple", type = "l"))
legend("topright", c("Sub_metering_1","Sub_metering_2","Sub_metering_3"), col = c(1,"red","purple"), pch = c("-","-","-"))
dev.copy(png,"plot2.png",width=480, height = 480, units = "px")
dev.off()
